In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.1'

In [ ]:
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

[1 2 3 4 5]
(5,)
int32
1
4


In [ ]:
print(a[0])
a[0]=99
print(a)

99
[99  2  3  4  5]


In [ ]:
b=a*np.array([2,3,1,1,1])

In [ ]:
b.sum()

216

In [ ]:
l=[1,2,3,4]

In [ ]:
print(l*2)
a*2

[1, 2, 3, 4, 1, 2, 3, 4]


array([198,   4,   6,   8,  10])

In [ ]:
a=np.array([1,2])
b=np.array([3,4])
dot=np.dot(a,b)
print(dot)

11


In [ ]:
a@b

11

In [ ]:
from timeit import default_timer as timer
# start=timer

In [ ]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(a[0])
print(a[0][0])
print(a[0,:])

[[1 2]
 [3 4]]
(2, 2)
[1 2]
1
[1 2]


In [ ]:
print(a.T)


[[1 3]
 [2 4]]


In [ ]:
b=np.array([[4,8],[5,6]])
c=a@b
print(c)

[[14 20]
 [32 48]]


In [ ]:
np.linalg.det(a)
np.linalg.inv(a)
print(a)
c=np.diag(a)
print(c)

[[1 2]
 [3 4]]
[1 4]


In [ ]:
cc=np.diag([1,9])
cc

array([[1, 0],
       [0, 9]])

In [ ]:
print(a[1,1])
print(a[a>=2])


4
[2 3 4]


In [ ]:
a=np.array([10,20,30,40,50,61])
b=a[[1,3,4]]
b

array([20, 40, 50])

In [ ]:
even_in_a=np.argwhere(a%2==0).flatten()
even_in_a
a=a.reshape((3,2))
a

array([[10, 20],
       [30, 40],
       [50, 61]])

In [ ]:
b=a*2
b
c=np.concatenate((a,b),axis=0)
print(c)

cc=np.concatenate((a,b),axis=1)
print(cc)


[[ 10  20]
 [ 30  40]
 [ 50  61]
 [ 20  40]
 [ 60  80]
 [100 122]]
[[ 10  20  20  40]
 [ 30  40  60  80]
 [ 50  61 100 122]]


In [ ]:
#broadcasting
a=np.array([[1,2,3],[4,5,7],[7,8,9],[4,5,6]])
b=np.array([1,0,1])
print(a)
print(a.sum(axis=1))
print(a.mean(axis=0))

[[1 2 3]
 [4 5 7]
 [7 8 9]
 [4 5 6]]
[ 6 16 24 15]
[4.   5.   6.25]


In [ ]:
c=np.full((4,4),5)
c

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
gg=np.random.random((3,2))
gg9=np.random.choice(5,size=10)
gg9

array([0, 1, 3, 3, 1, 4, 1, 0, 0, 1])

In [ ]:
A=np.array([[1,1],[1.5,4]])
b=np.array([1,2])

x=np.linalg.solve(A,b)
print(x)
print(A@x)

[0.8 0.2]
[1. 2.]
